dist: xenial

language: python
python:
  - "3.7"

before_install:
  - "cp config.yaml.example config.yaml"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest
